package modelo;
// Generated Mar 6, 2022 12:08:00 AM by Hibernate Tools 4.3.1



/**
 * DetalleFactura generated by hbm2java
 */
public class DetalleFactura  implements java.io.Serializable {


     private int idDetalleFactura;
     private CabezeraFactura cabezeraFactura;
     private Producto producto;
     private double total;
     private double iva;
     private double subtotal;

    public DetalleFactura() {
    }

	
    public DetalleFactura(int idDetalleFactura, double total, double iva, double subtotal) {
        this.idDetalleFactura = idDetalleFactura;
        this.total = total;
        this.iva = iva;
        this.subtotal = subtotal;
    }
    public DetalleFactura(int idDetalleFactura, CabezeraFactura cabezeraFactura, Producto producto, double total, double iva, double subtotal) {
       this.idDetalleFactura = idDetalleFactura;
       this.cabezeraFactura = cabezeraFactura;
       this.producto = producto;
       this.total = total;
       this.iva = iva;
       this.subtotal = subtotal;
    }
   
    public int getIdDetalleFactura() {
        return this.idDetalleFactura;
    }
    
    public void setIdDetalleFactura(int idDetalleFactura) {
        this.idDetalleFactura = idDetalleFactura;
    }
    public CabezeraFactura getCabezeraFactura() {
        return this.cabezeraFactura;
    }
    
    public void setCabezeraFactura(CabezeraFactura cabezeraFactura) {
        this.cabezeraFactura = cabezeraFactura;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public double getIva() {
        return this.iva;
    }
    
    public void setIva(double iva) {
        this.iva = iva;
    }
    public double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }




}


